### ISSUE TITLE
Temp directory cleanup issue

### ISSUE THREAD

**Issue by fidian** [tests-always-included/wick#11]
May have a bug where temp directories are cleaned up when they should not.  It appears that the on-exit hooks are executed at the end of subshells too, which means this script would fail.

    temp-directory A
    (
        temp-directory B
    )
    # A should still exist, B can optionally exist but I'd like it gone
    [[ ! -d "$A" ]] && echo "Missing temp directory A:  $A"

**Comment by fidian** [comment]
As a note, the PID of the shell could be tracked and the cleanup scripts could be skipped if the PIDs don't match.  First off, I should thoroughly check to confirm this is a bug.

**Comment by baelish** [comment]
I noticed an issue with the temp dir clean up as well. I suspect what I noticed is an issue in the on-exit command. It appears when the on exit item is 0 or 1 the action is performed if its anything higher it is not.
Server build data showing temp dir related entries:
http://gitlab.kearney.co.uk/snippets/8
Full build data in case you need anything more specific.
http://gitlab.kearney.co.uk/snippets/7

**Comment by fidian** [comment]
I have rewritten how the on-exit hooks work.  They now add to an array of commands and the array is associated to the specific process ID of the shell or subshell.  More manual testing will help ensure this is working and then I'll push my commit.
