### ISSUE TITLE
Please clarify workflow

### ISSUE THREAD

**Issue by vaporup** [tests-always-included/wick#123]
Hi,

I used many systems in the past. Puppet, Salt, Ansible, cdist, ... and I'm curious about Wick and read its documentation but still don't get the workflow.

- Is it run over SSH from a master node like in Ansible?
- Do you copy or check out the Wick code at the target system and run it?
- How do I differentiate between target hosts?

**Comment by fidian** [comment]
Excellent questions.

Wick is ran on the target machine. It currently has no way to remotely target another machine, though that thought was part of the considerations during its foundation. There just hasn't been any demand, though I'd be happy to help work on it if you have a particular need for it.

Currently we copy Wick and our own set of formulas to a target machine and execute Wick. This is done by hand, with Vagrant, or with Packer. Other methods would work as well.

Does this answer your questions well enough? Would you like additional clarifications?

**Comment by vaporup** [comment]
That's a good summary. Thank you very much
